# Use the Debian image as the base image
FROM debian:bullseye

# Copy the application source code into the container's /opt/lechacal directory
COPY src/ /opt/lechacal

# Install build dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        python \
        make \
        g++ \
        gcc \
        libc6-dev \
        linux-headers-amd64 \
        libudev-dev \
        nodejs \
        npm \
        && rm -rf /var/lib/apt/lists/*

# Change to the application directory and install the 'serialport' package and other Node.js dependencies
RUN cd /opt/lechacal && \
    npm install serialport && \
    npm install

# Set the working directory for the application
WORKDIR /opt/lechacal

# Define the default command to run when the container starts
CMD ["/bin/sh", "/opt/lechacal/server.sh"]
