# Use the Debian image as the base image
FROM debian:bullseye

# Copy the application source code into the container's /opt/lechacal directory
COPY src/ /opt/lechacal

# Install build dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        python \
        make \
        g++ \
        gcc \
        libc6-dev \
        linux-headers-arm32v4 \
        libudev-dev \
        nodejs \
        npm \
        && rm -rf /var/lib/apt/lists/*

# Change to the application directory
WORKDIR /opt/lechacal

# Install the 'serialport' package and other Node.js dependencies
RUN npm install serialport

# Install other Node.js dependencies
RUN npm install

# Define the default command to run when the container starts
CMD ["/bin/sh", "/opt/lechacal/server.sh"]
